### ISSUE TITLE
Macam mana nak apply

### ISSUE THREAD

**Issue by aminmahat** [azimabid00/epg#4]
Dah try copy and paste link tu takleh boleh guna ada kena setting pape ke sebelum nak paste tu atau boleh tak reply link tu kat bawah ni

**Comment by aminmahat** [comment]
https://raw.githubusercontent.com/azimabid00/epg/main/astro_epg.xml

Ni link yang saya copy

**Comment by Arsyad1105** [comment]
Masuk kat app apa?

**Comment by aminmahat** [comment]
Ott navigator

**Comment by Arsyad1105** [comment]
Settings > EPG Teleguide > User-provided EPG sources > Append user-provided source

Paste kat situ

**Comment by aminmahat** [comment]
Takleh lah boss dah buat step tu and then reload but takda progress

![Screenshot_2023-12-18-18-07-57-244_studio scillarium ottnavigator](https://github.com/azimabid00/epg/assets/124176311/12485d06-cfe3-4393-a62f-f51e4699d90f)

**Comment by aminmahat** [comment]
Boleh bagi video step ?

**Comment by Arsyad1105** [comment]
> Boleh bagi video step ?


https://github.com/azimabid00/epg/assets/65513499/98997e03-dd89-497a-b310-8896feff7349

**Comment by aminmahat** [comment]
Tak boleh jugak lah still kena add provider dulu kan before paste dekat user provide source? Sebab option EPG Teleguide takda kalau tak add provider

**Comment by Arsyad1105** [comment]
Ya kena add provider baru boleh guna

**Comment by Arsyad1105** [comment]
Tak. URL provider tu .m3u kena cari/beli/buat sendiri. Yang ni xml untuk TV guide saja. Bukan untuk tengok tv.
