### ISSUE TITLE
Unifi EPG incomplete.

### ISSUE THREAD

**Issue by Arsyad1105** [azimabid00/epg#8]
Some channel in epg not available: Cartoon Network, Nickelodeon, Bein sports 2 (bein 3 and 4 misaligned with both 2 and 3), ZEE Thirai, All HBO channels, Cinemax and HGTV.

**Comment by azimabid00** [comment]
Some channels are incomplete because of the account used to generate the epg is not bind to any paid UnifiTV id. Unless someone else is willing to donate any paid account, this is the only channels that can be fetched with what account I have now.

**Comment by Arsyad1105** [comment]
Isn't Nickelodeon available to subscribe for phone number users? And beIN 3 and 4 not available for users that registered under phone number right?

**Comment by azimabid00** [comment]
> Isn't Nickelodeon available to subscribe for phone number users?
I do not know about this, but I am not going to pay just to take the EPG data when I literally provide this for free. You can use the other EPG provided for this channel, just offset it by 5 minutes (iinm).

> And beIN 3 and 4 not available for users that registered under phone number right? 
I dont know.

> Also may I know how you fetch the epg?
Automated every day.
